# Generated by Django 2.1.3 on 2019-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programare',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
