# Generated by Django 2.1.3 on 2019-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0002_programare_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitaProgramare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('max_programari', models.IntegerField(default=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='programare',
            name='max_programari',
        ),
    ]
