# Generated by Django 2.1.3 on 2019-01-26 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0003_auto_20190126_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='programare',
            name='ora_programare',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
