# Generated by Django 2.1.3 on 2019-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0004_programare_ora_programare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimitaProgramare',
        ),
        migrations.AddField(
            model_name='programare',
            name='max_programari',
            field=models.IntegerField(default=8),
        ),
    ]
