# Generated by Django 2.1.3 on 2019-01-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0005_auto_20190126_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programare',
            name='max_programari',
        ),
    ]
