# Generated by Django 2.1.3 on 2019-01-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0006_remove_programare_max_programari'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaliiZi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10, unique=True)),
                ('max_programari', models.IntegerField(default=8)),
                ('start_time', models.IntegerField(default=10)),
                ('end_time', models.IntegerField(default=22)),
            ],
        ),
    ]
