# Generated by Django 2.1.3 on 2019-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0008_auto_20190126_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programare',
            options={'ordering': ['ora_programare']},
        ),
        migrations.AlterField(
            model_name='programare',
            name='telefon',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
