# Generated by Django 2.1.3 on 2018-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_quote',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
