# Generated by Django 3.2.7 on 2021-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist_temptation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptation',
            name='gave_in_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temptation',
            name='resisted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='temptation',
            unique_together={('temptation',)},
        ),
        migrations.RemoveField(
            model_name='temptation',
            name='last_resisted_time',
        ),
    ]
