# Generated by Django 3.2.7 on 2021-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist_temptation', '0002_auto_20210906_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptation',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
