# Generated by Django 3.2.7 on 2021-09-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist_temptation', '0004_auto_20210906_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptation',
            name='added_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
