# Generated by Django 3.2.7 on 2021-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist_temptation', '0006_alter_temptation_added_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temptation',
            options={'ordering': ('added_time', 'temptation')},
        ),
        migrations.AddField(
            model_name='temptation',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
