# Generated by Django 3.2.7 on 2021-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resist_temptation', '0007_auto_20210907_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.CharField(max_length=255)),
                ('added_time', models.DateField()),
                ('performed_count', models.IntegerField(default=-1)),
                ('username', models.CharField(default='admin', max_length=255)),
                ('ignore', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('added_time', 'habit'),
            },
        ),
    ]
