# Generated by Django 2.2 on 2019-05-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0002_auto_20190501_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='nume',
            new_name='name',
        ),
    ]
