# Generated by Django 2.2 on 2019-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('nume', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0', max_length=10)),
                ('appointment_time', models.CharField(max_length=5, null=True)),
            ],
            options={
                'ordering': ['date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='DayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, unique=True)),
                ('max_appointments', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=11)),
            ],
        ),
    ]
