# Generated by Django 2.2 on 2019-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetails',
            name='start_time',
            field=models.CharField(max_length=5),
        ),
    ]
